import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';

export interface ReceiptPdfPayload {
  transactionId: string;
  txHash: string;
  sender: string;
  recipient: string;
  amount: string;
  token: string;
  fee: string;
  timestamp: string;
  status: string;
  conversationId: string | null;
  messageId: string | null;
  explorerUrl: string;
}

@Injectable()
export class ReceiptPdfGenerator {
  async generate(payload: ReceiptPdfPayload): Promise<Buffer> {
    const doc = new PDFDocument({ margin: 48, size: 'A4' });
    const chunks: Buffer[] = [];

    return new Promise<Buffer>((resolve, reject) => {
      doc.on('data', (chunk) => chunks.push(chunk as Buffer));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.fontSize(22).text('WHSPR Stellar', { align: 'left' });
      doc.moveDown(0.2);
      doc.fontSize(16).text('Transaction Receipt');
      doc.moveDown();

      this.writeLine(doc, 'Transaction ID', payload.transactionId);
      this.writeLine(doc, 'Tx Hash', payload.txHash);
      this.writeLine(doc, 'Sender', payload.sender);
      this.writeLine(doc, 'Recipient', payload.recipient);
      this.writeLine(doc, 'Amount', `${payload.amount} ${payload.token}`);
      this.writeLine(doc, 'Network Fee', payload.fee);
      this.writeLine(doc, 'Timestamp', payload.timestamp);
      this.writeLine(doc, 'Status', payload.status);
      this.writeLine(doc, 'Conversation ID', payload.conversationId ?? 'N/A');
      this.writeLine(doc, 'Message ID', payload.messageId ?? 'N/A');
      this.writeLine(doc, 'Stellar Explorer', payload.explorerUrl);

      doc.moveDown(2);
      doc
        .fontSize(10)
        .fillColor('#6b7280')
        .text('This receipt is system-generated by WHSPR Stellar.', { align: 'left' });

      doc.end();
    });
  }

  private writeLine(doc: PDFKit.PDFDocument, label: string, value: string): void {
    doc.fontSize(11).fillColor('#111827').text(`${label}:`, { continued: true }).font('Helvetica');
    doc.text(` ${value}`);
    doc.moveDown(0.2);
  }
}
