import { MigrationInterface, QueryRunner } from "typeorm";

export class AddMessageThreading1769775808279 implements MigrationInterface {
    name = 'AddMessageThreading1769775808279'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "room_moderation_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roomId" character varying NOT NULL, "profanityFilterEnabled" boolean NOT NULL DEFAULT true, "spamDetectionEnabled" boolean NOT NULL DEFAULT true, "linkSpamDetectionEnabled" boolean NOT NULL DEFAULT true, "whitelistedWords" jsonb NOT NULL DEFAULT '[]', "blacklistedWords" jsonb NOT NULL DEFAULT '[]', "whitelistedDomains" jsonb NOT NULL DEFAULT '[]', "maxMessagesPerMinute" integer NOT NULL DEFAULT '5', "maxWarningsBeforeMute" integer NOT NULL DEFAULT '3', "autoMuteDuration" integer NOT NULL DEFAULT '60', "spamThreshold" integer NOT NULL DEFAULT '0.7', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f98c56e3a1b124ccfd3a8ac8a37" UNIQUE ("roomId"), CONSTRAINT "PK_c2a32f71d81dabd6f51d7d6baf9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "moderation_warnings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "roomId" character varying NOT NULL, "reason" character varying NOT NULL, "count" integer NOT NULL DEFAULT '1', "lastWarningAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_07e36ddd96d9137c2cb42e38a61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."flagged_messages_status_enum" AS ENUM('pending', 'approved', 'rejected', 'auto_removed')`);
        await queryRunner.query(`CREATE TABLE "flagged_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "messageId" character varying NOT NULL, "roomId" character varying NOT NULL, "userId" character varying NOT NULL, "content" text NOT NULL, "reason" text NOT NULL, "status" "public"."flagged_messages_status_enum" NOT NULL DEFAULT 'pending', "reportedBy" character varying, "reviewedBy" character varying, "moderatorNotes" text, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9e97b9b204696d307792e11a70c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."reports_type_enum" AS ENUM('spam', 'harassment', 'inappropriate', 'hate_speech', 'violence', 'impersonation', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_status_enum" AS ENUM('pending', 'under_review', 'resolved', 'dismissed', 'appealed')`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reporterId" uuid NOT NULL, "reportedUserId" uuid NOT NULL, "type" "public"."reports_type_enum" NOT NULL, "description" text NOT NULL, "status" "public"."reports_status_enum" NOT NULL DEFAULT 'pending', "moderatorNotes" character varying, "reviewedBy" uuid, "reviewedAt" TIMESTAMP, "appealReason" character varying, "appealedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4353be8309ce86650def2f8572" ON "reports" ("reporterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c88d2686339ad6d166620b741a" ON "reports" ("reportedUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dab4d78b3be05c1ca4a626f57f" ON "reports" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."moderation_rules_type_enum" AS ENUM('profanity', 'spam', 'link_spam', 'custom')`);
        await queryRunner.query(`CREATE TYPE "public"."moderation_rules_action_enum" AS ENUM('warn', 'delete', 'mute', 'ban')`);
        await queryRunner.query(`CREATE TABLE "moderation_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."moderation_rules_type_enum" NOT NULL, "action" "public"."moderation_rules_action_enum" NOT NULL, "config" jsonb, "isActive" boolean NOT NULL DEFAULT true, "priority" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_92eac042752719d816ad5dd30d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "blocked_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "blockerId" uuid NOT NULL, "blockedUserId" uuid NOT NULL, "reason" character varying, "blockedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_93760d788a31b7546c5424f42cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_afa68b24561a874954c8f89b04" ON "blocked_users" ("blockerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7c4a96e4f9f5adc7b22cf521d7" ON "blocked_users" ("blockedUserId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4ee7d7a668c7311238751c8917" ON "blocked_users" ("blockerId", "blockedUserId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TYPE "public"."users_visibility_enum" AS ENUM('public', 'private', 'friends')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(50) NOT NULL, "email" character varying, "displayName" character varying(100), "bio" text, "avatarCid" character varying, "avatarUrl" character varying, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "visibility" "public"."users_visibility_enum" NOT NULL DEFAULT 'public', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "lastActiveAt" TIMESTAMP, "currentXp" integer NOT NULL DEFAULT '0', "level" integer NOT NULL DEFAULT '1', "isPremium" boolean NOT NULL DEFAULT false, "xpMultiplier" numeric(3,2) NOT NULL DEFAULT '1', "preferred_chain" character varying, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE INDEX "IDX_49c5b098acf02a13f88d2017b0" ON "users" ("level") `);
        await queryRunner.query(`CREATE TABLE "streaks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "current_streak" integer NOT NULL DEFAULT '0', "longest_streak" integer NOT NULL DEFAULT '0', "last_login_date" date, "freeze_items" integer NOT NULL DEFAULT '0', "grace_period_end" TIMESTAMP, "streak_multiplier" numeric(3,2) NOT NULL DEFAULT '1', "total_days_logged" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7ef06a4f4177b11885dd5fb8b29" UNIQUE ("user_id"), CONSTRAINT "REL_7ef06a4f4177b11885dd5fb8b2" UNIQUE ("user_id"), CONSTRAINT "PK_52547016a1a6409f6e5287ed859" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7ef06a4f4177b11885dd5fb8b2" ON "streaks" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."xp_history_action_enum" AS ENUM('MESSAGE_SENT', 'ROOM_CREATED', 'PROFILE_COMPLETED', 'AVATAR_UPLOADED', 'FRIEND_ADDED', 'REACTION_GIVEN', 'ROOM_JOINED', 'DAILY_LOGIN')`);
        await queryRunner.query(`CREATE TABLE "xp_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "amount" integer NOT NULL, "action" "public"."xp_history_action_enum" NOT NULL, "description" text, "levelBefore" integer NOT NULL DEFAULT '0', "levelAfter" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c4361b4eac7662c2e46cdb164d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_80584b6b884a9838de5f238141" ON "xp_history" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8eb6246bfe4637c90fe6874365" ON "xp_history" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."streak_rewards_rewardtype_enum" AS ENUM('xp', 'token', 'badge', 'premium')`);
        await queryRunner.query(`CREATE TABLE "streak_rewards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "milestone" integer NOT NULL, "rewardType" "public"."streak_rewards_rewardtype_enum" NOT NULL, "rewardAmount" integer, "rewardDescription" character varying(100), "claimed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a2564afdac155d08ee8c47a3dca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0e46858b15dc671fafabd130db" ON "streak_rewards" ("user_id", "milestone") `);
        await queryRunner.query(`CREATE INDEX "IDX_199c3fc4f0d8548c7576c5ef5c" ON "streak_rewards" ("user_id", "claimed_at") `);
        await queryRunner.query(`CREATE TYPE "public"."streak_history_action_enum" AS ENUM('login', 'increment', 'reset', 'freeze_used', 'grace_period_used', 'reward_claimed')`);
        await queryRunner.query(`CREATE TABLE "streak_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "action" "public"."streak_history_action_enum" NOT NULL, "streakBefore" integer, "streakAfter" integer, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a3b49547a898f9048078b829e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3f1754afbf24f93ab83dc2babe" ON "streak_history" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."streak_badges_badgetype_enum" AS ENUM('streak_3', 'streak_7', 'streak_14', 'streak_30', 'streak_60', 'streak_100', 'streak_365', 'longest_streak_10', 'longest_streak_30', 'longest_streak_100')`);
        await queryRunner.query(`CREATE TABLE "streak_badges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "badgeType" "public"."streak_badges_badgetype_enum" NOT NULL, "description" character varying(200), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_be7d1dff15a65089eaec4eb53ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d1f38efec39c47c70b0925bef8" ON "streak_badges" ("user_id", "badgeType") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "resource" character varying, "action" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."roles_name_enum" AS ENUM('admin', 'moderator', 'user', 'creator')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" "public"."roles_name_enum" NOT NULL, "description" character varying, "hierarchy" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."transfers_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."transfers_type_enum" AS ENUM('p2p', 'bulk')`);
        await queryRunner.query(`CREATE TABLE "transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sender_id" uuid NOT NULL, "recipient_id" uuid NOT NULL, "amount" numeric(18,8) NOT NULL, "blockchain_network" character varying NOT NULL DEFAULT 'stellar', "transaction_hash" character varying, "status" "public"."transfers_status_enum" NOT NULL DEFAULT 'pending', "type" "public"."transfers_type_enum" NOT NULL DEFAULT 'p2p', "memo" text, "note" text, "bulk_transfer_id" character varying, "sender_balance_before" numeric(18,8), "sender_balance_after" numeric(18,8), "recipient_balance_before" numeric(18,8), "recipient_balance_after" numeric(18,8), "failure_reason" text, "retry_count" integer NOT NULL DEFAULT '0', "completed_at" TIMESTAMP, "failed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e3ac488c2cfaab7978c3347e59d" UNIQUE ("transaction_hash"), CONSTRAINT "PK_f712e908b465e0085b4408cabc3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e3ac488c2cfaab7978c3347e59" ON "transfers" ("transaction_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_d4ed29295a0fb8993eac7038b6" ON "transfers" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_15aea92a7612ba7d309eff2607" ON "transfers" ("recipient_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_42f9ec3edb48c0930205d20efd" ON "transfers" ("sender_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "transfer_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "name" character varying NOT NULL, "description" text, "recipient_id" character varying NOT NULL, "amount" numeric(18,8) NOT NULL, "blockchain_network" character varying NOT NULL DEFAULT 'stellar', "memo" text, "note" text, "use_count" integer NOT NULL DEFAULT '0', "last_used_at" TIMESTAMP, "is_favorite" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5c21bed6d4c8fd54db4f3df0c60" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f9ac29acd1a56560ec3c03abf3" ON "transfer_templates" ("user_id", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_27280d140cfdf9f291bd973520" ON "transfer_templates" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."transfer_limits_period_enum" AS ENUM('daily', 'weekly', 'monthly')`);
        await queryRunner.query(`CREATE TABLE "transfer_limits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "period" "public"."transfer_limits_period_enum" NOT NULL, "limit_amount" numeric(18,8) NOT NULL, "used_amount" numeric(18,8) NOT NULL DEFAULT '0', "transaction_count" integer NOT NULL DEFAULT '0', "max_transaction_count" integer, "period_start" TIMESTAMP NOT NULL, "period_end" TIMESTAMP NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_033edf087bdd18bf9fff799d1a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3419f48d49fcd3340e1c56ba0a" ON "transfer_limits" ("user_id", "period") `);
        await queryRunner.query(`CREATE TYPE "public"."transfer_disputes_reason_enum" AS ENUM('unauthorized', 'wrong_amount', 'wrong_recipient', 'not_received', 'duplicate', 'fraud', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."transfer_disputes_status_enum" AS ENUM('open', 'under_review', 'resolved', 'rejected', 'closed')`);
        await queryRunner.query(`CREATE TABLE "transfer_disputes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transfer_id" uuid NOT NULL, "initiator_id" uuid NOT NULL, "reason" "public"."transfer_disputes_reason_enum" NOT NULL, "description" text NOT NULL, "status" "public"."transfer_disputes_status_enum" NOT NULL DEFAULT 'open', "resolution" text, "resolved_by" character varying, "resolved_at" TIMESTAMP, "evidence" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4effdf800f331b0930b1f585085" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e834ba09e82963fec6e6000c51" ON "transfer_disputes" ("initiator_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3b3cb94f1c2284d52e23a17b5" ON "transfer_disputes" ("transfer_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."scheduled_transfers_recurrencefrequency_enum" AS ENUM('daily', 'weekly', 'biweekly', 'monthly', 'quarterly', 'yearly')`);
        await queryRunner.query(`CREATE TYPE "public"."scheduled_transfers_status_enum" AS ENUM('pending', 'executed', 'cancelled', 'failed')`);
        await queryRunner.query(`CREATE TABLE "scheduled_transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sender_id" uuid NOT NULL, "recipient_id" character varying NOT NULL, "amount" numeric(18,8) NOT NULL, "blockchain_network" character varying NOT NULL DEFAULT 'stellar', "memo" text, "note" text, "scheduled_date" TIMESTAMP NOT NULL, "is_recurring" boolean NOT NULL DEFAULT false, "recurrenceFrequency" "public"."scheduled_transfers_recurrencefrequency_enum", "recurrence_end_date" TIMESTAMP, "next_execution_date" TIMESTAMP, "execution_count" integer NOT NULL DEFAULT '0', "max_executions" integer, "status" "public"."scheduled_transfers_status_enum" NOT NULL DEFAULT 'pending', "last_transfer_id" character varying, "executed_at" TIMESTAMP, "cancelled_at" TIMESTAMP, "cancelled_by" character varying, "cancellation_reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_90ec38022a3e6cfb3db3e7bd466" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9e16bcf3ed0dc0682d2a4833aa" ON "scheduled_transfers" ("is_recurring", "next_execution_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b6b6ee81999cd2d40eda230bf" ON "scheduled_transfers" ("status", "scheduled_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_775124cab1a2abec31072cbf5f" ON "scheduled_transfers" ("sender_id", "scheduled_date") `);
        await queryRunner.query(`CREATE TYPE "public"."bulk_transfers_status_enum" AS ENUM('pending', 'processing', 'completed', 'partially_completed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "bulk_transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sender_id" uuid NOT NULL, "total_recipients" integer NOT NULL, "total_amount" numeric(18,8) NOT NULL, "successful_transfers" integer NOT NULL DEFAULT '0', "failed_transfers" integer NOT NULL DEFAULT '0', "status" "public"."bulk_transfers_status_enum" NOT NULL DEFAULT 'pending', "blockchain_network" character varying NOT NULL DEFAULT 'stellar', "memo" text, "completed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aa7da335c36fddc0ddad1fde6a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b885c643103411b0404e5a5232" ON "bulk_transfers" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_93d39cf6d501c372685caafc34" ON "bulk_transfers" ("sender_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying NOT NULL, "user_id" uuid NOT NULL, "refresh_token" character varying, "ip_address" character varying, "user_agent" text, "device_type" character varying, "device_name" character varying, "browser" character varying, "os" character varying, "device_fingerprint" character varying, "location" jsonb, "is_active" boolean NOT NULL DEFAULT true, "last_activity" TIMESTAMP NOT NULL DEFAULT now(), "expires_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e9f62f5dcb8a54b84234c9e7a06" UNIQUE ("token"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9f62f5dcb8a54b84234c9e7a0" ON "sessions" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_988b9e434a536256a4fee3ad68" ON "sessions" ("user_id", "is_active") `);
        await queryRunner.query(`CREATE TABLE "rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "creatorId" uuid NOT NULL, "expiryTimestamp" bigint, "durationMinutes" integer, "isExpired" boolean NOT NULL DEFAULT false, "warningNotificationSent" boolean NOT NULL DEFAULT false, "extensionCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ce5b6690233a32f836d340a3f7" ON "rooms" ("expiryTimestamp") `);
        await queryRunner.query(`CREATE TYPE "public"."room_payments_status_enum" AS ENUM('pending', 'completed', 'failed', 'refunded', 'expired')`);
        await queryRunner.query(`CREATE TABLE "room_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "room_id" uuid NOT NULL, "user_id" uuid NOT NULL, "amount" numeric(18,8) NOT NULL, "platform_fee" numeric(18,8) NOT NULL, "creator_amount" numeric(18,8) NOT NULL, "transaction_hash" character varying NOT NULL, "blockchain_network" character varying NOT NULL DEFAULT 'ethereum', "status" "public"."room_payments_status_enum" NOT NULL DEFAULT 'pending', "access_granted" boolean NOT NULL DEFAULT false, "access_expires_at" TIMESTAMP, "refund_transaction_hash" character varying, "refunded_at" TIMESTAMP, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8cab3fe80190f65649d251f95e7" UNIQUE ("transaction_hash"), CONSTRAINT "PK_93cc71b554e9277d877450a73e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."room_members_role_enum" AS ENUM('OWNER', 'ADMIN', 'MODERATOR', 'MEMBER')`);
        await queryRunner.query(`CREATE TYPE "public"."room_members_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'REMOVED')`);
        await queryRunner.query(`CREATE TABLE "room_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roomId" uuid NOT NULL, "userId" uuid NOT NULL, "role" "public"."room_members_role_enum" NOT NULL DEFAULT 'MEMBER', "status" "public"."room_members_status_enum" NOT NULL DEFAULT 'ACTIVE', "permissions" text, "inviteToken" character varying, "inviteStatus" character varying NOT NULL DEFAULT 'ACCEPTED', "joinedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "lastActivityAt" TIMESTAMP, "kickReason" text, "kickedAt" TIMESTAMP, "kickedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_151cb61c3e462093aa3b8e70f7b" UNIQUE ("roomId", "userId"), CONSTRAINT "PK_4493fab0433f741b7cf842e6038" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0ff12cce7b2ec29a284ee956d4" ON "room_members" ("roomId", "role") `);
        await queryRunner.query(`CREATE INDEX "IDX_ca3c84760fb37c2f14658a0a2e" ON "room_members" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a27f901523ddfa2eaecb16a597" ON "room_members" ("roomId") `);
        await queryRunner.query(`CREATE TYPE "public"."room_invitations_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'REVOKED')`);
        await queryRunner.query(`CREATE TABLE "room_invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roomId" uuid NOT NULL, "invitedById" uuid NOT NULL, "invitedUserId" uuid, "invitedEmail" character varying, "status" "public"."room_invitations_status_enum" NOT NULL DEFAULT 'PENDING', "inviteToken" character varying NOT NULL, "message" text, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "acceptedAt" TIMESTAMP, "rejectedAt" TIMESTAMP, "rejectionReason" text, CONSTRAINT "UQ_f73081933d8f56d67bb9af855b1" UNIQUE ("inviteToken"), CONSTRAINT "PK_53e419056c5457582eb6b20bf85" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a152798f1f760c135938802d04" ON "room_invitations" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e30363636b63b7791af11ab17" ON "room_invitations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f25f5479c121499909172ec0d5" ON "room_invitations" ("invitedUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9b9696d0041af08392b2ae4ab1" ON "room_invitations" ("roomId") `);
        await queryRunner.query(`CREATE TABLE "user_room_access" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "room_id" uuid NOT NULL, "has_access" boolean NOT NULL DEFAULT false, "is_free_trial" boolean NOT NULL DEFAULT false, "access_expires_at" TIMESTAMP, "payment_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ce843e7e99af618450f4262fa42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f251b3c81bf7b8e335d13c20e5" ON "user_room_access" ("user_id", "room_id") `);
        await queryRunner.query(`CREATE TABLE "room_whitelists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roomId" uuid NOT NULL, "userId" uuid NOT NULL, "addedBy" uuid NOT NULL, "notes" text, "addedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1b4578568350156981c364db91a" UNIQUE ("roomId", "userId"), CONSTRAINT "PK_d36c5deef9ccd7ac5ebb933213b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a665e3cd6e0a618f68d011d183" ON "room_whitelists" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_329f4e3463f9254216e6a75ce2" ON "room_whitelists" ("roomId") `);
        await queryRunner.query(`CREATE TABLE "room_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "messagePermission" character varying NOT NULL DEFAULT 'all', "readOnly" boolean NOT NULL DEFAULT false, "slowModeSeconds" integer NOT NULL DEFAULT '0', "allowLinks" boolean NOT NULL DEFAULT true, "allowMedia" boolean NOT NULL DEFAULT true, "notificationsEnabled" boolean NOT NULL DEFAULT true, "themeColor" character varying, "roomIcon" character varying, "welcomeMessage" text, "roomDescription" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "roomId" uuid, CONSTRAINT "PK_fb913b7bdd1647711cd6fcc849a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."room_emergency_pauses_reason_enum" AS ENUM('SPAM', 'ABUSE', 'SECURITY', 'MAINTENANCE', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "room_emergency_pauses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roomId" uuid NOT NULL, "pausedBy" uuid NOT NULL, "reason" "public"."room_emergency_pauses_reason_enum" NOT NULL DEFAULT 'OTHER', "description" text, "isPaused" boolean NOT NULL DEFAULT true, "resumedAt" TIMESTAMP, "resumedBy" uuid, "pausedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_953b9ea40ace0771a61bb21c6de" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1ca0a2907937c6cae807236c47" ON "room_emergency_pauses" ("roomId", "isPaused") `);
        await queryRunner.query(`CREATE INDEX "IDX_6f20255eca2abb8974dbd76f6a" ON "room_emergency_pauses" ("roomId") `);
        await queryRunner.query(`CREATE TABLE "room_bans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roomId" uuid NOT NULL, "userId" uuid NOT NULL, "bannedBy" uuid NOT NULL, "reason" text, "expiresAt" TIMESTAMP, "bannedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c92968d50abe6ed1d9a3364e5f1" UNIQUE ("roomId", "userId"), CONSTRAINT "PK_f9d925f0f4d6ce338e967a299e0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_61e77f07472d1f25f2194c9f2b" ON "room_bans" ("roomId", "bannedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c816c4cce8f709165187b6fb2e" ON "room_bans" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4ddcc53b3247c634c352603dc0" ON "room_bans" ("roomId") `);
        await queryRunner.query(`CREATE TABLE "room_analytics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date" date NOT NULL, "totalMessages" integer NOT NULL DEFAULT '0', "uniqueActiveMembers" integer NOT NULL DEFAULT '0', "hourlyActivity" jsonb NOT NULL DEFAULT '{}', "topContributors" jsonb NOT NULL DEFAULT '[]', "newMembers" integer NOT NULL DEFAULT '0', "activeReturnMembers" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "roomId" uuid, CONSTRAINT "PK_afc3245b785f20b86ba05965215" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_12992f3934b977fd0aef0cbe2b" ON "room_analytics" ("roomId", "date") `);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "type" character varying NOT NULL DEFAULT 'text', "fileUrl" character varying, "fileName" character varying, "isEdited" boolean NOT NULL DEFAULT false, "isDeleted" boolean NOT NULL DEFAULT false, "metadata" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "roomId" uuid, "senderId" uuid, CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3e270107016add269af85a3012" ON "messages" ("roomId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "pinned_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pinnedAt" TIMESTAMP NOT NULL DEFAULT now(), "roomId" uuid, "messageId" uuid, CONSTRAINT "PK_f27ff551aca1df5eb7af6079b67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rewards_type_enum" AS ENUM('xp_boost', 'premium_days', 'custom_badge')`);
        await queryRunner.query(`CREATE TABLE "rewards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."rewards_type_enum" NOT NULL, "value" numeric(10,2) NOT NULL, "description" text, "name" character varying(255), "imageUrl" character varying(500), "stackLimit" integer NOT NULL DEFAULT '0', "expirationDays" integer, "isActive" boolean NOT NULL DEFAULT true, "isTradeable" boolean NOT NULL DEFAULT false, "isGiftable" boolean NOT NULL DEFAULT false, "isMarketplaceItem" boolean NOT NULL DEFAULT false, "marketplacePrice" numeric(10,2), "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3d947441a48debeb9b7366f8b8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5f25483a120b4731ac8e1720d1" ON "rewards" ("type") `);
        await queryRunner.query(`CREATE TYPE "public"."user_rewards_status_enum" AS ENUM('active', 'redeemed', 'expired', 'traded', 'gifted')`);
        await queryRunner.query(`CREATE TABLE "user_rewards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "rewardId" uuid NOT NULL, "status" "public"."user_rewards_status_enum" NOT NULL DEFAULT 'active', "expiresAt" TIMESTAMP, "redeemedAt" TIMESTAMP, "tradedToUserId" uuid, "giftedToUserId" uuid, "grantedByUserId" uuid, "eventName" character varying(255), "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_86078010f64a891601beef7c54f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b6605c2dc37c321e0b4c4388c9" ON "user_rewards" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_afd173bfe5ee9dd4ad46aac1ed" ON "user_rewards" ("rewardId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_55788bd13d945e5d865eca29cc" ON "user_rewards" ("userId", "expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_b63efc7c27b9ffc6b120aed826" ON "user_rewards" ("userId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."reward_marketplace_status_enum" AS ENUM('active', 'sold', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "reward_marketplace" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sellerId" uuid NOT NULL, "userRewardId" uuid NOT NULL, "price" numeric(10,2) NOT NULL, "status" "public"."reward_marketplace_status_enum" NOT NULL DEFAULT 'active', "buyerId" uuid, "soldAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_74a48c45a74e78d67a90a279cc9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_69f6886686720ecdf44bbf8f41" ON "reward_marketplace" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a63ad7eadbb09be9fab9de56e2" ON "reward_marketplace" ("status", "price") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a2c86c0ac6b5591cc3d468d24" ON "reward_marketplace" ("sellerId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."quests_questtype_enum" AS ENUM('daily', 'weekly', 'special')`);
        await queryRunner.query(`CREATE TYPE "public"."quests_rewardtype_enum" AS ENUM('xp', 'token', 'both')`);
        await queryRunner.query(`CREATE TABLE "quests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying NOT NULL, "requirement" character varying NOT NULL, "requirementCount" integer NOT NULL, "questType" "public"."quests_questtype_enum" NOT NULL, "rewardType" "public"."quests_rewardtype_enum" NOT NULL, "rewardAmount" integer NOT NULL, "activeUntil" TIMESTAMP NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a037497017b64f530fe09c75364" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_quest_progress" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "questId" uuid NOT NULL, "currentProgress" integer NOT NULL DEFAULT '0', "isCompleted" boolean NOT NULL DEFAULT false, "isClaimed" boolean NOT NULL DEFAULT false, "completedAt" TIMESTAMP, "claimedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_68b19cc8d0db2cddc6061746d7b" UNIQUE ("userId", "questId"), CONSTRAINT "PK_201dda0520db698521cb9cbfda6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quest_progress" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "questId" character varying NOT NULL, "progress" integer NOT NULL DEFAULT '0', "target" integer NOT NULL, "completed" boolean NOT NULL DEFAULT false, "percentage" double precision NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_00270f6acd4a18f1c6ae6aa216a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "push_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "endpoint" character varying NOT NULL, "p256dhKey" text NOT NULL, "authKey" text NOT NULL, "deviceType" character varying, "deviceName" character varying, "userAgent" character varying, "isActive" boolean NOT NULL DEFAULT true, "lastUsedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_757fc8f00c34f66832668dc2e53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2f5d4d507bdde51a8a44d20788" ON "push_subscriptions" ("userId", "isActive") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('message', 'mention', 'reply', 'reaction', 'room_invite', 'room_join', 'room_leave', 'reward_granted', 'level_up', 'achievement', 'system')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_priority_enum" AS ENUM('low', 'normal', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipientId" uuid NOT NULL, "senderId" uuid, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "data" jsonb, "priority" "public"."notifications_priority_enum" NOT NULL DEFAULT 'normal', "isRead" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP, "actionUrl" character varying, "imageUrl" character varying, "expiresAt" TIMESTAMP, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1846a75fabf533d10bf09142af" ON "notifications" ("isRead", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_1728a6c5f9753540f2f0f16153" ON "notifications" ("type", "recipientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba953fe98c085411bba8535299" ON "notifications" ("recipientId", "isRead", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_preferences_type_enum" AS ENUM('message', 'mention', 'reply', 'reaction', 'room_invite', 'room_join', 'room_leave', 'reward_granted', 'level_up', 'achievement', 'system')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_preferences_channel_enum" AS ENUM('in_app', 'push', 'email', 'sms')`);
        await queryRunner.query(`CREATE TABLE "notification_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" "public"."notification_preferences_type_enum" NOT NULL, "channel" "public"."notification_preferences_channel_enum" NOT NULL, "isEnabled" boolean NOT NULL DEFAULT true, "quietHoursStart" TIME, "quietHoursEnd" TIME, "mutedRooms" text, "mutedUsers" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5e498be60b9875dcd31c2c53d92" UNIQUE ("userId", "type", "channel"), CONSTRAINT "PK_e94e2b543f2f218ee68e4f4fad2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c1045c5ab68629da776b58cb76" ON "notification_preferences" ("userId", "type") `);
        await queryRunner.query(`CREATE TABLE "message_edit_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "messageId" uuid NOT NULL, "previousContent" text NOT NULL, "newContent" text NOT NULL, "editedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bfa5f0ef6d425ab3ba923e82940" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "message_reactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "messageId" uuid NOT NULL, "userId" uuid NOT NULL, "type" character varying NOT NULL, "isCustom" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a3ef25d82b03629050fddeb4fbf" UNIQUE ("messageId", "userId", "type"), CONSTRAINT "PK_654a9f0059ff93a8f156be66a5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8debda83e8a0b8d60c90d087a1" ON "message_reactions" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_d35f71680dd89cd399d6eb5477" ON "message_reactions" ("messageId", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec655dbc7a845d792c6d5d7f85" ON "message_reactions" ("messageId", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."leaderboard_entries_category_enum" AS ENUM('xp', 'tips_sent', 'messages')`);
        await queryRunner.query(`CREATE TYPE "public"."leaderboard_entries_timeframe_enum" AS ENUM('daily', 'weekly', 'all_time')`);
        await queryRunner.query(`CREATE TABLE "leaderboard_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "username" character varying NOT NULL, "score" numeric(10,2) NOT NULL DEFAULT '0', "rank" integer NOT NULL DEFAULT '0', "category" "public"."leaderboard_entries_category_enum" NOT NULL, "timeframe" "public"."leaderboard_entries_timeframe_enum" NOT NULL DEFAULT 'all_time', "roomId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "lastResetAt" TIMESTAMP, CONSTRAINT "PK_a3187f7d37819756a5519336665" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e0e0d8d4021f8b3dc45d98d67c" ON "leaderboard_entries" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a44ab25d7c545c7c701af6f93e" ON "leaderboard_entries" ("roomId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_775d748797a613de4fb7b01324" ON "leaderboard_entries" ("userId", "category", "timeframe", "roomId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe3b961a5c225fcfb0c5547916" ON "leaderboard_entries" ("category", "timeframe", "roomId", "score") `);
        await queryRunner.query(`CREATE TABLE "session_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "publicKey" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "revoked" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_d7535bb7f5458745afa01b42ad1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."gasless_transactions_status_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "gasless_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "to" character varying NOT NULL, "xdr" text NOT NULL, "nonce" integer NOT NULL, "status" "public"."gasless_transactions_status_enum" NOT NULL DEFAULT 'PENDING', "txHash" character varying, "retries" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c3d39d6e25caceb27e01751408a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gas_budgets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "dailyLimit" integer NOT NULL DEFAULT '100000', "used" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_86333f0400b4113e7e6d9922243" UNIQUE ("userId"), CONSTRAINT "PK_9f6c9cae3de2db28e10c0c3e86d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('user.banned', 'user.unbanned', 'user.suspended', 'user.unsuspended', 'user.verified', 'user.unverified', 'user.viewed', 'user.updated', 'user.deleted', 'bulk.action', 'impersonation.started', 'impersonation.ended')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" "public"."audit_logs_action_enum" NOT NULL, "adminId" uuid NOT NULL, "targetUserId" uuid, "details" text, "metadata" jsonb, "ipAddress" inet, "userAgent" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."achievements_type_enum" AS ENUM('first_message', '100_messages', '500_messages', '1000_messages', 'room_creator', '10_rooms', 'early_adopter', 'night_owl', 'social_butterfly', 'conversation_starter', 'veteran', 'legend')`);
        await queryRunner.query(`CREATE TYPE "public"."achievements_rarity_enum" AS ENUM('common', 'uncommon', 'rare', 'epic', 'legendary')`);
        await queryRunner.query(`CREATE TABLE "achievements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text NOT NULL, "type" "public"."achievements_type_enum" NOT NULL, "criteria" jsonb NOT NULL, "icon" character varying, "rarity" "public"."achievements_rarity_enum" NOT NULL DEFAULT 'common', "xpBonus" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "isHidden" boolean NOT NULL DEFAULT false, "displayOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b2d2ec6547a003ee5b43a71dbe3" UNIQUE ("name"), CONSTRAINT "UQ_6261fe3636483beee9db8fd3707" UNIQUE ("type"), CONSTRAINT "PK_1bc19c37c6249f70186f318d71d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_achievements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "achievementId" uuid NOT NULL, "progress" double precision NOT NULL DEFAULT '0', "currentValue" integer NOT NULL DEFAULT '0', "targetValue" integer, "isUnlocked" boolean NOT NULL DEFAULT false, "unlockedAt" TIMESTAMP, "notificationSent" boolean NOT NULL DEFAULT false, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3d94aba7e9ed55365f68b5e77fa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ac6bc9da3e8a56f3f7082012d" ON "user_achievements" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c1acd69cf91b1e353634c152dd" ON "user_achievements" ("userId", "achievementId") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "displayName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "bio"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatarCid"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatarUrl"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "visibility"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastActiveAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "currentXp"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49c5b098acf02a13f88d2017b0"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "level"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isPremium"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "xpMultiplier"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "preferred_chain"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "fileUrl"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "senderId"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "username" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "displayName" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "bio" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatarCid" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatarUrl" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" "public"."users_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`CREATE TYPE "public"."users_visibility_enum" AS ENUM('public', 'private', 'friends')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "visibility" "public"."users_visibility_enum" NOT NULL DEFAULT 'public'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastActiveAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "currentXp" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "level" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isPremium" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "xpMultiplier" numeric(3,2) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "preferred_chain" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isEmailVerified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "emailVerificationToken" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "emailVerificationExpires" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "passwordResetToken" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "passwordResetExpires" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "loginAttempts" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lockoutUntil" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "refreshToken" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isBanned" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "bannedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "bannedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD "banReason" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "suspendedUntil" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "suspendedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "suspendedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD "suspensionReason" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isVerified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "verifiedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "verifiedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "ownerId" uuid`);
        await queryRunner.query(`CREATE TYPE "public"."rooms_roomtype_enum" AS ENUM('PUBLIC', 'PRIVATE', 'TOKEN_GATED', 'TIMED')`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "roomType" "public"."rooms_roomtype_enum" NOT NULL DEFAULT 'PUBLIC'`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "isPrivate" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "icon" character varying`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "maxMembers" integer NOT NULL DEFAULT '500'`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "memberCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "is_token_gated" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "entry_fee" numeric(18,8) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "token_address" character varying`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "payment_required" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "free_trial_enabled" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "free_trial_duration_hours" integer NOT NULL DEFAULT '24'`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "access_duration_days" integer`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "fileUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "metadata" jsonb NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "senderId" uuid`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "conversationId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "authorId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "mediaUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "originalContent" text`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "editedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "deletedBy" character varying`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "isHardDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "parentId" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rooms" ALTER COLUMN "creatorId" DROP NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e270107016add269af85a3012"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "roomId"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "roomId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."messages_type_enum" AS ENUM('text', 'image', 'file', 'tip', 'system')`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "type" "public"."messages_type_enum" NOT NULL DEFAULT 'text'`);
        await queryRunner.query(`CREATE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE INDEX "IDX_49c5b098acf02a13f88d2017b0" ON "users" ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e270107016add269af85a3012" ON "messages" ("roomId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_6772fcdccb66bcce0bbbff9939" ON "messages" ("type", "conversationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_086675be1da8dcf849b24017a6" ON "messages" ("isDeleted", "conversationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_39c6d293e07eede467206b2dbb" ON "messages" ("authorId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_751332fc6cc6fc576c6975cd07" ON "messages" ("conversationId", "createdAt") `);
        await queryRunner.query(`ALTER TABLE "streaks" ADD CONSTRAINT "FK_7ef06a4f4177b11885dd5fb8b29" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "xp_history" ADD CONSTRAINT "FK_80584b6b884a9838de5f238141a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "streak_rewards" ADD CONSTRAINT "FK_d2e2e97f8334c935697551d242c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "streak_history" ADD CONSTRAINT "FK_056fb29a367a9c7923622209e05" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "streak_badges" ADD CONSTRAINT "FK_4319d9d4d760bd8cf8a17e4c8dc" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_f7f67b6fc0dbefadee6433e7876" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfers" ADD CONSTRAINT "FK_1b9bc151f26ab591eda36ba39d2" FOREIGN KEY ("recipient_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_templates" ADD CONSTRAINT "FK_831f8d03766581f6aa369b6a27b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_limits" ADD CONSTRAINT "FK_d3727418bef322d3ddd71f415dd" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_disputes" ADD CONSTRAINT "FK_55c3efc5054c1995d2c92dfe4d0" FOREIGN KEY ("transfer_id") REFERENCES "transfers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_disputes" ADD CONSTRAINT "FK_66f7b3d21bc7187ee31b90e173f" FOREIGN KEY ("initiator_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_transfers" ADD CONSTRAINT "FK_b8bc9540627151416e66877a556" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bulk_transfers" ADD CONSTRAINT "FK_7c2128972cc903648eda01f582c" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_payments" ADD CONSTRAINT "FK_5a2e7c9f94a24798662411ff7e1" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_payments" ADD CONSTRAINT "FK_3fd164d961c84215061187cc57c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_members" ADD CONSTRAINT "FK_a27f901523ddfa2eaecb16a5976" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_members" ADD CONSTRAINT "FK_ca3c84760fb37c2f14658a0a2ec" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_invitations" ADD CONSTRAINT "FK_9b9696d0041af08392b2ae4ab1e" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_invitations" ADD CONSTRAINT "FK_35d74327cb7c660f040ecd32d5c" FOREIGN KEY ("invitedById") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_invitations" ADD CONSTRAINT "FK_f25f5479c121499909172ec0d59" FOREIGN KEY ("invitedUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_383ac461c63dd52c22ba73a6624" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_ffe6d736746b7177435e97a0fe9" FOREIGN KEY ("creatorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_room_access" ADD CONSTRAINT "FK_2a921926cdd77f65b9e39e6dc35" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_room_access" ADD CONSTRAINT "FK_b7525191129abd95b194faa79e3" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_whitelists" ADD CONSTRAINT "FK_329f4e3463f9254216e6a75ce2d" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_whitelists" ADD CONSTRAINT "FK_a665e3cd6e0a618f68d011d183b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_whitelists" ADD CONSTRAINT "FK_d670358aad1833a1de884dccc51" FOREIGN KEY ("addedBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_settings" ADD CONSTRAINT "FK_081870e11035c5c73e4de84eb33" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_emergency_pauses" ADD CONSTRAINT "FK_6f20255eca2abb8974dbd76f6a6" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_emergency_pauses" ADD CONSTRAINT "FK_0739228329e5c442e317d1f1eef" FOREIGN KEY ("pausedBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_emergency_pauses" ADD CONSTRAINT "FK_dc97460b94ac23c49726deecded" FOREIGN KEY ("resumedBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_bans" ADD CONSTRAINT "FK_4ddcc53b3247c634c352603dc0c" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_bans" ADD CONSTRAINT "FK_c816c4cce8f709165187b6fb2e5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_bans" ADD CONSTRAINT "FK_e6b50159410f8739e9c74a7d47f" FOREIGN KEY ("bannedBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_analytics" ADD CONSTRAINT "FK_4f2709447b41565d6f44c067d68" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_aaa8a6effc7bd20a1172d3a3bc8" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pinned_messages" ADD CONSTRAINT "FK_0d15bc78513e40d887a7c569989" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pinned_messages" ADD CONSTRAINT "FK_7fa21cd035cc98de8a785e31e56" FOREIGN KEY ("messageId") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_rewards" ADD CONSTRAINT "FK_d538de4678c82491e5a8a8a5834" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_rewards" ADD CONSTRAINT "FK_d2904b4fa623c996161687e47d1" FOREIGN KEY ("rewardId") REFERENCES "rewards"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reward_marketplace" ADD CONSTRAINT "FK_e5e5ac2e9664fa47b959b2cd0d4" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reward_marketplace" ADD CONSTRAINT "FK_ef1fae3c7f38f67bd7761ed5380" FOREIGN KEY ("userRewardId") REFERENCES "user_rewards"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_quest_progress" ADD CONSTRAINT "FK_a54a32b57a6bfc2c03afd4687df" FOREIGN KEY ("questId") REFERENCES "quests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ADD CONSTRAINT "FK_4cc061875e9eecc311a94b3e431" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_db873ba9a123711a4bff527ccd5" FOREIGN KEY ("recipientId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_ddb7981cf939fe620179bfea33a" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "FK_b70c44e8b00757584a393225593" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_edit_history" ADD CONSTRAINT "FK_a11cec7974e3bc0ee90f533110b" FOREIGN KEY ("messageId") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_reactions" ADD CONSTRAINT "FK_7623d77216e8457a552490259e0" FOREIGN KEY ("messageId") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_reactions" ADD CONSTRAINT "FK_82d59cb474d00eea46d7e192f28" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_819e6bb0ee78baf73c398dc707f" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_7d473d0de3669832052cac98b98" FOREIGN KEY ("parentId") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_9d53d8c4d4227c02e4476129d25" FOREIGN KEY ("adminId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_5b7fbc8045a0654e5f8db27dc5c" FOREIGN KEY ("targetUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_achievements" ADD CONSTRAINT "FK_6a5a5816f54d0044ba5f3dc2b74" FOREIGN KEY ("achievementId") REFERENCES "achievements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "user_achievements" DROP CONSTRAINT "FK_6a5a5816f54d0044ba5f3dc2b74"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_5b7fbc8045a0654e5f8db27dc5c"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_9d53d8c4d4227c02e4476129d25"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_7d473d0de3669832052cac98b98"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_819e6bb0ee78baf73c398dc707f"`);
        await queryRunner.query(`ALTER TABLE "message_reactions" DROP CONSTRAINT "FK_82d59cb474d00eea46d7e192f28"`);
        await queryRunner.query(`ALTER TABLE "message_reactions" DROP CONSTRAINT "FK_7623d77216e8457a552490259e0"`);
        await queryRunner.query(`ALTER TABLE "message_edit_history" DROP CONSTRAINT "FK_a11cec7974e3bc0ee90f533110b"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "FK_b70c44e8b00757584a393225593"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_ddb7981cf939fe620179bfea33a"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_db873ba9a123711a4bff527ccd5"`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" DROP CONSTRAINT "FK_4cc061875e9eecc311a94b3e431"`);
        await queryRunner.query(`ALTER TABLE "user_quest_progress" DROP CONSTRAINT "FK_a54a32b57a6bfc2c03afd4687df"`);
        await queryRunner.query(`ALTER TABLE "reward_marketplace" DROP CONSTRAINT "FK_ef1fae3c7f38f67bd7761ed5380"`);
        await queryRunner.query(`ALTER TABLE "reward_marketplace" DROP CONSTRAINT "FK_e5e5ac2e9664fa47b959b2cd0d4"`);
        await queryRunner.query(`ALTER TABLE "user_rewards" DROP CONSTRAINT "FK_d2904b4fa623c996161687e47d1"`);
        await queryRunner.query(`ALTER TABLE "user_rewards" DROP CONSTRAINT "FK_d538de4678c82491e5a8a8a5834"`);
        await queryRunner.query(`ALTER TABLE "pinned_messages" DROP CONSTRAINT "FK_7fa21cd035cc98de8a785e31e56"`);
        await queryRunner.query(`ALTER TABLE "pinned_messages" DROP CONSTRAINT "FK_0d15bc78513e40d887a7c569989"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_aaa8a6effc7bd20a1172d3a3bc8"`);
        await queryRunner.query(`ALTER TABLE "room_analytics" DROP CONSTRAINT "FK_4f2709447b41565d6f44c067d68"`);
        await queryRunner.query(`ALTER TABLE "room_bans" DROP CONSTRAINT "FK_e6b50159410f8739e9c74a7d47f"`);
        await queryRunner.query(`ALTER TABLE "room_bans" DROP CONSTRAINT "FK_c816c4cce8f709165187b6fb2e5"`);
        await queryRunner.query(`ALTER TABLE "room_bans" DROP CONSTRAINT "FK_4ddcc53b3247c634c352603dc0c"`);
        await queryRunner.query(`ALTER TABLE "room_emergency_pauses" DROP CONSTRAINT "FK_dc97460b94ac23c49726deecded"`);
        await queryRunner.query(`ALTER TABLE "room_emergency_pauses" DROP CONSTRAINT "FK_0739228329e5c442e317d1f1eef"`);
        await queryRunner.query(`ALTER TABLE "room_emergency_pauses" DROP CONSTRAINT "FK_6f20255eca2abb8974dbd76f6a6"`);
        await queryRunner.query(`ALTER TABLE "room_settings" DROP CONSTRAINT "FK_081870e11035c5c73e4de84eb33"`);
        await queryRunner.query(`ALTER TABLE "room_whitelists" DROP CONSTRAINT "FK_d670358aad1833a1de884dccc51"`);
        await queryRunner.query(`ALTER TABLE "room_whitelists" DROP CONSTRAINT "FK_a665e3cd6e0a618f68d011d183b"`);
        await queryRunner.query(`ALTER TABLE "room_whitelists" DROP CONSTRAINT "FK_329f4e3463f9254216e6a75ce2d"`);
        await queryRunner.query(`ALTER TABLE "user_room_access" DROP CONSTRAINT "FK_b7525191129abd95b194faa79e3"`);
        await queryRunner.query(`ALTER TABLE "user_room_access" DROP CONSTRAINT "FK_2a921926cdd77f65b9e39e6dc35"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_ffe6d736746b7177435e97a0fe9"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_383ac461c63dd52c22ba73a6624"`);
        await queryRunner.query(`ALTER TABLE "room_invitations" DROP CONSTRAINT "FK_f25f5479c121499909172ec0d59"`);
        await queryRunner.query(`ALTER TABLE "room_invitations" DROP CONSTRAINT "FK_35d74327cb7c660f040ecd32d5c"`);
        await queryRunner.query(`ALTER TABLE "room_invitations" DROP CONSTRAINT "FK_9b9696d0041af08392b2ae4ab1e"`);
        await queryRunner.query(`ALTER TABLE "room_members" DROP CONSTRAINT "FK_ca3c84760fb37c2f14658a0a2ec"`);
        await queryRunner.query(`ALTER TABLE "room_members" DROP CONSTRAINT "FK_a27f901523ddfa2eaecb16a5976"`);
        await queryRunner.query(`ALTER TABLE "room_payments" DROP CONSTRAINT "FK_3fd164d961c84215061187cc57c"`);
        await queryRunner.query(`ALTER TABLE "room_payments" DROP CONSTRAINT "FK_5a2e7c9f94a24798662411ff7e1"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`ALTER TABLE "bulk_transfers" DROP CONSTRAINT "FK_7c2128972cc903648eda01f582c"`);
        await queryRunner.query(`ALTER TABLE "scheduled_transfers" DROP CONSTRAINT "FK_b8bc9540627151416e66877a556"`);
        await queryRunner.query(`ALTER TABLE "transfer_disputes" DROP CONSTRAINT "FK_66f7b3d21bc7187ee31b90e173f"`);
        await queryRunner.query(`ALTER TABLE "transfer_disputes" DROP CONSTRAINT "FK_55c3efc5054c1995d2c92dfe4d0"`);
        await queryRunner.query(`ALTER TABLE "transfer_limits" DROP CONSTRAINT "FK_d3727418bef322d3ddd71f415dd"`);
        await queryRunner.query(`ALTER TABLE "transfer_templates" DROP CONSTRAINT "FK_831f8d03766581f6aa369b6a27b"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_1b9bc151f26ab591eda36ba39d2"`);
        await queryRunner.query(`ALTER TABLE "transfers" DROP CONSTRAINT "FK_f7f67b6fc0dbefadee6433e7876"`);
        await queryRunner.query(`ALTER TABLE "streak_badges" DROP CONSTRAINT "FK_4319d9d4d760bd8cf8a17e4c8dc"`);
        await queryRunner.query(`ALTER TABLE "streak_history" DROP CONSTRAINT "FK_056fb29a367a9c7923622209e05"`);
        await queryRunner.query(`ALTER TABLE "streak_rewards" DROP CONSTRAINT "FK_d2e2e97f8334c935697551d242c"`);
        await queryRunner.query(`ALTER TABLE "xp_history" DROP CONSTRAINT "FK_80584b6b884a9838de5f238141a"`);
        await queryRunner.query(`ALTER TABLE "streaks" DROP CONSTRAINT "FK_7ef06a4f4177b11885dd5fb8b29"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_751332fc6cc6fc576c6975cd07"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39c6d293e07eede467206b2dbb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_086675be1da8dcf849b24017a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6772fcdccb66bcce0bbbff9939"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e270107016add269af85a3012"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49c5b098acf02a13f88d2017b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."messages_type_enum"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "type" character varying NOT NULL DEFAULT 'text'`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "roomId"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "roomId" uuid`);
        await queryRunner.query(`CREATE INDEX "IDX_3e270107016add269af85a3012" ON "messages" ("roomId", "createdAt") `);
        await queryRunner.query(`ALTER TABLE "rooms" ALTER COLUMN "creatorId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "parentId"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "isHardDeleted"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "deletedBy"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "editedAt"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "originalContent"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "mediaUrl"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "conversationId"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "senderId"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "fileUrl"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "access_duration_days"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "free_trial_duration_hours"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "free_trial_enabled"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "payment_required"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "token_address"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "entry_fee"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "is_token_gated"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "memberCount"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "maxMembers"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "icon"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "isPrivate"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "roomType"`);
        await queryRunner.query(`DROP TYPE "public"."rooms_roomtype_enum"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "verifiedBy"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "verifiedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isVerified"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "suspensionReason"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "suspendedBy"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "suspendedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "suspendedUntil"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "banReason"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "bannedBy"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "bannedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isBanned"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "refreshToken"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lockoutUntil"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "loginAttempts"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "passwordResetExpires"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "passwordResetToken"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "emailVerificationExpires"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "emailVerificationToken"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isEmailVerified"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "preferred_chain"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "xpMultiplier"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isPremium"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "level"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "currentXp"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastActiveAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "visibility"`);
        await queryRunner.query(`DROP TYPE "public"."users_visibility_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatarUrl"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatarCid"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "bio"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "displayName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "senderId" uuid`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "metadata" jsonb NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "fileUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "preferred_chain" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "xpMultiplier" numeric(3,2) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isPremium" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "level" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`CREATE INDEX "IDX_49c5b098acf02a13f88d2017b0" ON "users" ("level") `);
        await queryRunner.query(`ALTER TABLE "users" ADD "currentXp" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastActiveAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "visibility" "public"."users_visibility_enum" NOT NULL DEFAULT 'public'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" "public"."users_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatarUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatarCid" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "bio" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "displayName" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "username" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username")`);
        await queryRunner.query(`CREATE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1acd69cf91b1e353634c152dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ac6bc9da3e8a56f3f7082012d"`);
        await queryRunner.query(`DROP TABLE "user_achievements"`);
        await queryRunner.query(`DROP TABLE "achievements"`);
        await queryRunner.query(`DROP TYPE "public"."achievements_rarity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."achievements_type_enum"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP TABLE "gas_budgets"`);
        await queryRunner.query(`DROP TABLE "gasless_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."gasless_transactions_status_enum"`);
        await queryRunner.query(`DROP TABLE "session_keys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe3b961a5c225fcfb0c5547916"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775d748797a613de4fb7b01324"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a44ab25d7c545c7c701af6f93e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0e0d8d4021f8b3dc45d98d67c"`);
        await queryRunner.query(`DROP TABLE "leaderboard_entries"`);
        await queryRunner.query(`DROP TYPE "public"."leaderboard_entries_timeframe_enum"`);
        await queryRunner.query(`DROP TYPE "public"."leaderboard_entries_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec655dbc7a845d792c6d5d7f85"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d35f71680dd89cd399d6eb5477"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8debda83e8a0b8d60c90d087a1"`);
        await queryRunner.query(`DROP TABLE "message_reactions"`);
        await queryRunner.query(`DROP TABLE "message_edit_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1045c5ab68629da776b58cb76"`);
        await queryRunner.query(`DROP TABLE "notification_preferences"`);
        await queryRunner.query(`DROP TYPE "public"."notification_preferences_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_preferences_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba953fe98c085411bba8535299"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1728a6c5f9753540f2f0f16153"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1846a75fabf533d10bf09142af"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f5d4d507bdde51a8a44d20788"`);
        await queryRunner.query(`DROP TABLE "push_subscriptions"`);
        await queryRunner.query(`DROP TABLE "quest_progress"`);
        await queryRunner.query(`DROP TABLE "user_quest_progress"`);
        await queryRunner.query(`DROP TABLE "quests"`);
        await queryRunner.query(`DROP TYPE "public"."quests_rewardtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."quests_questtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a2c86c0ac6b5591cc3d468d24"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a63ad7eadbb09be9fab9de56e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69f6886686720ecdf44bbf8f41"`);
        await queryRunner.query(`DROP TABLE "reward_marketplace"`);
        await queryRunner.query(`DROP TYPE "public"."reward_marketplace_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b63efc7c27b9ffc6b120aed826"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55788bd13d945e5d865eca29cc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_afd173bfe5ee9dd4ad46aac1ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6605c2dc37c321e0b4c4388c9"`);
        await queryRunner.query(`DROP TABLE "user_rewards"`);
        await queryRunner.query(`DROP TYPE "public"."user_rewards_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f25483a120b4731ac8e1720d1"`);
        await queryRunner.query(`DROP TABLE "rewards"`);
        await queryRunner.query(`DROP TYPE "public"."rewards_type_enum"`);
        await queryRunner.query(`DROP TABLE "pinned_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e270107016add269af85a3012"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12992f3934b977fd0aef0cbe2b"`);
        await queryRunner.query(`DROP TABLE "room_analytics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ddcc53b3247c634c352603dc0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c816c4cce8f709165187b6fb2e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61e77f07472d1f25f2194c9f2b"`);
        await queryRunner.query(`DROP TABLE "room_bans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f20255eca2abb8974dbd76f6a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ca0a2907937c6cae807236c47"`);
        await queryRunner.query(`DROP TABLE "room_emergency_pauses"`);
        await queryRunner.query(`DROP TYPE "public"."room_emergency_pauses_reason_enum"`);
        await queryRunner.query(`DROP TABLE "room_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_329f4e3463f9254216e6a75ce2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a665e3cd6e0a618f68d011d183"`);
        await queryRunner.query(`DROP TABLE "room_whitelists"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f251b3c81bf7b8e335d13c20e5"`);
        await queryRunner.query(`DROP TABLE "user_room_access"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b9696d0041af08392b2ae4ab1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f25f5479c121499909172ec0d5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e30363636b63b7791af11ab17"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a152798f1f760c135938802d04"`);
        await queryRunner.query(`DROP TABLE "room_invitations"`);
        await queryRunner.query(`DROP TYPE "public"."room_invitations_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a27f901523ddfa2eaecb16a597"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca3c84760fb37c2f14658a0a2e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ff12cce7b2ec29a284ee956d4"`);
        await queryRunner.query(`DROP TABLE "room_members"`);
        await queryRunner.query(`DROP TYPE "public"."room_members_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."room_members_role_enum"`);
        await queryRunner.query(`DROP TABLE "room_payments"`);
        await queryRunner.query(`DROP TYPE "public"."room_payments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce5b6690233a32f836d340a3f7"`);
        await queryRunner.query(`DROP TABLE "rooms"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_988b9e434a536256a4fee3ad68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9f62f5dcb8a54b84234c9e7a0"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93d39cf6d501c372685caafc34"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b885c643103411b0404e5a5232"`);
        await queryRunner.query(`DROP TABLE "bulk_transfers"`);
        await queryRunner.query(`DROP TYPE "public"."bulk_transfers_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775124cab1a2abec31072cbf5f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b6b6ee81999cd2d40eda230bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e16bcf3ed0dc0682d2a4833aa"`);
        await queryRunner.query(`DROP TABLE "scheduled_transfers"`);
        await queryRunner.query(`DROP TYPE "public"."scheduled_transfers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."scheduled_transfers_recurrencefrequency_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3b3cb94f1c2284d52e23a17b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e834ba09e82963fec6e6000c51"`);
        await queryRunner.query(`DROP TABLE "transfer_disputes"`);
        await queryRunner.query(`DROP TYPE "public"."transfer_disputes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transfer_disputes_reason_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3419f48d49fcd3340e1c56ba0a"`);
        await queryRunner.query(`DROP TABLE "transfer_limits"`);
        await queryRunner.query(`DROP TYPE "public"."transfer_limits_period_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27280d140cfdf9f291bd973520"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9ac29acd1a56560ec3c03abf3"`);
        await queryRunner.query(`DROP TABLE "transfer_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42f9ec3edb48c0930205d20efd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15aea92a7612ba7d309eff2607"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4ed29295a0fb8993eac7038b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3ac488c2cfaab7978c3347e59"`);
        await queryRunner.query(`DROP TABLE "transfers"`);
        await queryRunner.query(`DROP TYPE "public"."transfers_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transfers_status_enum"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_name_enum"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1f38efec39c47c70b0925bef8"`);
        await queryRunner.query(`DROP TABLE "streak_badges"`);
        await queryRunner.query(`DROP TYPE "public"."streak_badges_badgetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f1754afbf24f93ab83dc2babe"`);
        await queryRunner.query(`DROP TABLE "streak_history"`);
        await queryRunner.query(`DROP TYPE "public"."streak_history_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_199c3fc4f0d8548c7576c5ef5c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e46858b15dc671fafabd130db"`);
        await queryRunner.query(`DROP TABLE "streak_rewards"`);
        await queryRunner.query(`DROP TYPE "public"."streak_rewards_rewardtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8eb6246bfe4637c90fe6874365"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80584b6b884a9838de5f238141"`);
        await queryRunner.query(`DROP TABLE "xp_history"`);
        await queryRunner.query(`DROP TYPE "public"."xp_history_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ef06a4f4177b11885dd5fb8b2"`);
        await queryRunner.query(`DROP TABLE "streaks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49c5b098acf02a13f88d2017b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_visibility_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ee7d7a668c7311238751c8917"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c4a96e4f9f5adc7b22cf521d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_afa68b24561a874954c8f89b04"`);
        await queryRunner.query(`DROP TABLE "blocked_users"`);
        await queryRunner.query(`DROP TABLE "moderation_rules"`);
        await queryRunner.query(`DROP TYPE "public"."moderation_rules_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."moderation_rules_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dab4d78b3be05c1ca4a626f57f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c88d2686339ad6d166620b741a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4353be8309ce86650def2f8572"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_type_enum"`);
        await queryRunner.query(`DROP TABLE "flagged_messages"`);
        await queryRunner.query(`DROP TYPE "public"."flagged_messages_status_enum"`);
        await queryRunner.query(`DROP TABLE "moderation_warnings"`);
        await queryRunner.query(`DROP TABLE "room_moderation_settings"`);
    }

}
