const defaults: Record<string, string> = {
  NODE_ENV: 'test',
  PORT: '0',
  LOG_LEVEL: 'error',
  DATABASE_HOST: '127.0.0.1',
  DATABASE_PORT: '5432',
  DATABASE_USER: 'postgres',
  DATABASE_PASSWORD: 'postgres',
  DATABASE_NAME: 'gasless_gossip_test',
  DATABASE_POOL_MIN: '1',
  DATABASE_POOL_MAX: '4',
  JWT_SECRET: 'e2e-super-secret-key-that-is-at-least-thirty-two-chars',
  JWT_EXPIRES_IN: '15m',
  EVM_RPC_URL: 'https://example.invalid/rpc',
  EVM_PRIVATE_KEY: '0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
  EVM_ACCOUNT_ADDRESS: '0x1111111111111111111111111111111111111111',
  EVM_CONTRACT_ADDRESS: '0x2222222222222222222222222222222222222222',
  EVM_NETWORK: 'base',
  REDIS_HOST: '127.0.0.1',
  REDIS_PORT: '6379',
  REDIS_PASSWORD: '',
  REDIS_DB: '0',
  ADMIN_USER_IDS: '',
  ADMIN_WALLET_ADDRESSES: '',
  THROTTLE_TTL: '60',
  THROTTLE_LIMIT: '10',
  THROTTLE_LIMIT_SHORT: '3',
  THROTTLE_LIMIT_MEDIUM: '60',
  THROTTLE_LIMIT_LONG: '1000',
  CORS_ORIGIN: 'http://localhost:3000',
  STORAGE_PROVIDER: 's3',
  STORAGE_BUCKET: 'gasless-gossip-e2e',
  STORAGE_REGION: 'us-east-1',
  STORAGE_ENDPOINT: 'https://storage.invalid',
  STORAGE_ACCESS_KEY_ID: 'test-access-key',
  STORAGE_SECRET_ACCESS_KEY: 'test-secret-key',
  STORAGE_PUBLIC_BASE_URL: 'https://cdn.invalid',
  ATTACHMENT_PRESIGN_EXPIRY_SECONDS: '300',
  ATTACHMENT_MAX_SIZE_FREE_BYTES: '10485760',
  ATTACHMENT_MAX_SIZE_PREMIUM_BYTES: '26214400',
  ATTACHMENT_MAX_SIZE_VIP_BYTES: '52428800',
  ATTACHMENT_ALLOWED_MIME_TYPES:
    'image/jpeg,image/png,image/webp,image/gif,video/mp4,audio/mpeg,audio/wav,application/pdf',
  SOROBAN_RPC_URL: 'https://soroban-testnet.stellar.org:443',
  SOROBAN_NETWORK_PASSPHRASE: 'Test SDF Network ; September 2015',
  SOROBAN_CONTRACT_IDS: 'test-contract-id',
  STELLAR_HORIZON_MAINNET_URL: 'https://horizon.stellar.org',
  STELLAR_HORIZON_TESTNET_URL: 'https://horizon-testnet.stellar.org',
  JOB_BLOCKCHAIN_EVENT_POLLING_MS: '5000',
  JOB_TRANSACTION_STATUS_SYNC_MS: '30000',
  JOB_TOKEN_PRICE_REFRESH_MS: '60000',
  JOB_NFT_SYNC_MS: '600000',
  JOB_REFERRAL_REWARD_PROCESSING_MS: '3600000',
  JOB_WEBHOOK_DELIVERY_RETRY_MS: '300000',
  JOB_SESSION_CLEANUP_CRON: '0 2 * * *',
  JOB_TIER_EXPIRY_CHECK_CRON: '0 0 * * *',
  JOB_ANALYTICS_AGGREGATION_CRON: '0 0 * * *',
  JOB_AUDIT_LOG_CLEANUP_CRON: '0 0 * * 0',
  JOB_LOCK_TTL_MS: '15000',
  OTEL_ENABLED: 'false',
  OTEL_SERVICE_NAME: 'gasless-gossip-api-e2e',
  OTEL_EXPORTER_OTLP_ENDPOINT: 'http://127.0.0.1:4318/v1/traces',
};

for (const [key, value] of Object.entries(defaults)) {
  if (!process.env[key]) {
    process.env[key] = value;
  }
}
