export enum XpAction {
  MESSAGE_SENT = 'MESSAGE_SENT',
  ROOM_CREATED = 'ROOM_CREATED',
  PROFILE_COMPLETED = 'PROFILE_COMPLETED',
  AVATAR_UPLOADED = 'AVATAR_UPLOADED',
  FRIEND_ADDED = 'FRIEND_ADDED',
  REACTION_GIVEN = 'REACTION_GIVEN',
  ROOM_JOINED = 'ROOM_JOINED',
  DAILY_LOGIN = 'DAILY_LOGIN',
}

export const XP_VALUES: Record<XpAction, number> = {
  [XpAction.MESSAGE_SENT]: 10,
  [XpAction.ROOM_CREATED]: 50,
  [XpAction.PROFILE_COMPLETED]: 100,
  [XpAction.AVATAR_UPLOADED]: 25,
  [XpAction.FRIEND_ADDED]: 15,
  [XpAction.REACTION_GIVEN]: 5,
  [XpAction.ROOM_JOINED]: 20,
  [XpAction.DAILY_LOGIN]: 10,
};

export const XP_PER_LEVEL = 1000;

export const DAILY_XP_CAP_REGULAR = 1000;
export const DAILY_XP_CAP_PREMIUM = Number.MAX_SAFE_INTEGER;

export const PREMIUM_XP_MULTIPLIER = 1.5;
