export enum ActivityType {
  TRANSFER_RECEIVED = 'TRANSFER_RECEIVED',
  CONTACT_ACCEPTED = 'CONTACT_ACCEPTED',
  GROUP_INVITE = 'GROUP_INVITE',
  REPUTATION_CHANGE = 'REPUTATION_CHANGE',
  MENTION = 'MENTION',
  REACTION_TO_MESSAGE = 'REACTION_TO_MESSAGE',
  DAO_PROPOSAL_CREATED = 'DAO_PROPOSAL_CREATED',
}