// constants/onboarding-steps.ts
export enum OnboardingStep {
  WALLET_CONNECTED = 'WALLET_CONNECTED',
  PROFILE_COMPLETED = 'PROFILE_COMPLETED',
  USERNAME_SET = 'USERNAME_SET',
  FIRST_CONTACT_ADDED = 'FIRST_CONTACT_ADDED',
  FIRST_MESSAGE_SENT = 'FIRST_MESSAGE_SENT',
  ENCRYPTION_KEY_REGISTERED = 'ENCRYPTION_KEY_REGISTERED',
  FIRST_TRANSFER = 'FIRST_TRANSFER',
}