export enum QuestAction {
  SWAP_COMPLETED = 'SWAP_COMPLETED',
  WALLET_CONNECTED = 'WALLET_CONNECTED',
  TRADE_EXECUTED = 'TRADE_EXECUTED',
  SEND_MESSAGES = 'SEND_MESSAGES',
  CREATE_ROOM = 'CREATE_ROOM',
  TIP_USERS = 'TIP_USERS',
  DAILY_LOGIN = 'DAILY_LOGIN',
}
