# Generated by Django 4.2.27 on 2026-01-28 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhraseTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phrase", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=50)),
                ("usage_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "phrase_templates",
                "ordering": ["-usage_count"],
            },
        ),
        migrations.CreateModel(
            name="WordSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(db_index=True, max_length=100)),
                ("frequency", models.IntegerField(default=1)),
                ("context_words", models.JSONField(default=list)),
                ("language", models.CharField(default="en", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "word_suggestions",
                "ordering": ["-frequency"],
                "indexes": [
                    models.Index(
                        fields=["word", "frequency"], name="word_sugges_word_bfd63f_idx"
                    ),
                    models.Index(
                        fields=["language", "frequency"],
                        name="word_sugges_languag_8cac75_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserTypingPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                ("frequency", models.IntegerField(default=1)),
                ("last_used", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typing_patterns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_typing_patterns",
                "indexes": [
                    models.Index(
                        fields=["user", "frequency"],
                        name="user_typing_user_id_7e13da_idx",
                    )
                ],
                "unique_together": {("user", "word")},
            },
        ),
    ]
